vk_token: ""
classifier:
  show_images: false
  model_name: efficientnetv2-s
redis:
  host: localhost
  port: 6379
sinks: 
- firebase:   # sink name
  type: firebase
  config:
    name: firebase
    firebase_credentials_path: credentials/firebase-credentials.json
- postgres:   # sink name
  type: postgres
  config:
    name: postgres
    database: andysilv
    host: localhost
    user: andysilv
    password: ""
    port: 5432